# Generated by Django 3.2.8 on 2021-11-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcourse',
            name='courseHours',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
