# Generated by Django 3.2.8 on 2021-11-29 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_allcourse_coursehours'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherPending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('year', models.IntegerField(default=1)),
                ('email', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=100)),
                ('interest', models.CharField(max_length=100)),
                ('history', models.CharField(max_length=100)),
                ('portfolio', models.CharField(max_length=100)),
                ('applyDate', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile')),
            ],
        ),
    ]
