# Generated by Django 3.2.8 on 2021-11-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_teacherpending'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherpending',
            name='approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacherpending',
            name='approveDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
