# Generated by Django 3.2.8 on 2021-11-29 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20211129_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherpending',
            old_name='history',
            new_name='work',
        ),
    ]
