# Generated by Django 3.2.8 on 2022-02-22 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='videoUrl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
