# Generated by Django 3.2.8 on 2021-11-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_teacherpending_apply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherpending',
            name='apply',
        ),
        migrations.AddField(
            model_name='profile',
            name='apply',
            field=models.BooleanField(default=False),
        ),
    ]
