# Generated by Django 3.2.8 on 2021-11-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_homework_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcourse',
            name='courseTaken',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
