# Generated by Django 3.2.8 on 2021-11-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_allcourse_coursetaken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcourse',
            name='courseTaken',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
