# Generated by Django 3.2.8 on 2022-02-24 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_answer_question_quiz_result'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizes'},
        ),
    ]
