# Generated by Django 4.0.2 on 2022-03-22 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycourse',
            name='progress',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=19, null=True),
        ),
        migrations.DeleteModel(
            name='Progress',
        ),
    ]
