# Generated by Django 3.2.8 on 2022-03-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_mycourse_progress_delete_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycourse',
            name='numVideo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mycourse',
            name='progress',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19, null=True),
        ),
    ]
