# Generated by Django 3.2.8 on 2022-04-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_videoresult_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoresult',
            name='currentTime',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='videoresult',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
