# Generated by Django 3.2.8 on 2022-04-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20220401_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoresult',
            name='currentTime',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
