# Generated by Django 3.2.8 on 2022-04-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_allcourse_courserating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(choices=[('ง่าย', 'ง่าย'), ('ปานกลาง', 'ปานกลาง'), ('ยาก', 'ยาก')], max_length=7),
        ),
    ]
