# Generated by Django 3.2.8 on 2022-04-07 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20220407_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.allcourse'),
        ),
        migrations.AddField(
            model_name='result',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.lesson'),
        ),
    ]
