# Generated by Django 3.2.8 on 2022-04-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_result_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoresult',
            name='latest',
            field=models.BooleanField(default=False),
        ),
    ]
