# Generated by Django 3.2.8 on 2022-04-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_remove_videoresult_latest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcourse',
            name='courseHours',
            field=models.CharField(blank=True, choices=[('น้อยกว่า 1 ชั่วโมง', 'น้อยกว่า 1 ชั่วโมง'), ('1 - 2 ชั่วโมง', '1 - 2 ชั่วโมง'), ('2 - 3 ชั่วโมง', '2 - 3 ชั่วโมง'), ('3 - 4 ชั่วโมง', '3 - 4 ชั่วโมง'), ('มากกว่า 4 ชั่วโมง', 'มากกว่า 4 ชั่วโมง')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='allcourse',
            name='courseMajor',
            field=models.CharField(choices=[('dmt', 'Digital Media Technology'), ('gdm', 'Game Development'), ('mmi', 'Medical Media Innovation'), ('mdt', 'Media Technology')], max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='major',
            field=models.CharField(blank=True, choices=[('dmt', 'Digital Media Technology'), ('gdm', 'Game Development'), ('mmi', 'Medical Media Innovation')], max_length=100, null=True),
        ),
    ]
